# Generated by Django 4.1.5 on 2023-02-01 09:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('facebook', 'Facebook'),
                            ('instagram', 'Instagram'),
                            ('help', 'Написать в поддержку'),
                            ('user_agreement', 'Пользовательское соглашение'),
                            ('privacy_policy', 'Политика конфиденциальности'),
                            ('cookie_policy', 'Cookie Policy'),
                        ],
                        unique=True,
                    ),
                ),
                ('url', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('question', models.TextField()),
                ('question_ru', models.TextField(null=True)),
                ('question_en', models.TextField(null=True)),
                ('answer', models.TextField()),
                ('answer_ru', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'language',
                    models.TextField(
                        choices=[('ru', 'Русский'), ('en', 'Английский')], unique=True
                    ),
                ),
                ('json', models.JSONField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tags.category',
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('icon', models.ImageField(upload_to='pages/social_link/icon')),
                ('url', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageMentorSet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'index',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(19)]
                    ),
                ),
                (
                    'mentor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor'
                    ),
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='pages.page'
                    ),
                ),
            ],
            options={
                'db_table': 'page_mentor_set',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='mentor_set',
            field=models.ManyToManyField(
                through='pages.PageMentorSet', to='mentors.mentor'
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tags.tag',
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tag_set',
            field=models.ManyToManyField(
                related_name='page_set_by_tag_set', to='tags.tag'
            ),
        ),
    ]
