# Generated by Django 4.2.2 on 2023-06-27 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('facebook', 'Facebook'),
                            ('instagram', 'Instagram'),
                            ('help', 'Написать в поддержку'),
                            ('user_agreement', 'Пользовательское соглашение'),
                            ('privacy_policy', 'Политика конфиденциальности'),
                            ('cookie_policy', 'Cookie Policy'),
                        ],
                        unique=True,
                    ),
                ),
                ('url', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'language',
                    models.TextField(
                        choices=[('ru', 'Русский'), ('en', 'Английский')], unique=True
                    ),
                ),
                ('json', models.JSONField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageMentors',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'index',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(19)]
                    ),
                ),
            ],
            options={
                'db_table': 'page_mentors',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('icon', models.ImageField(upload_to='pages/social_link/icon')),
                ('url', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
