# Generated by Django 4.2.2 on 2023-06-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('mentors', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagementors',
            name='mentor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='page_mentors',
                to='mentors.mentor',
            ),
        ),
        migrations.AddField(
            model_name='pagementors',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='page_mentors',
                to='pages.page',
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pages',
                to='tags.category',
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='mentors',
            field=models.ManyToManyField(
                related_name='pages', through='pages.PageMentors', to='mentors.mentor'
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pages',
                to='tags.tag',
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(related_name='pages_by_tags', to='tags.tag'),
        ),
        migrations.AddConstraint(
            model_name='pagementors',
            constraint=models.UniqueConstraint(
                fields=('page', 'mentor'), name='unique_page_mentor'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagementors',
            constraint=models.UniqueConstraint(
                fields=('page', 'index'), name='unique_page_index'
            ),
        ),
    ]
