# Generated by Django 3.2.2 on 2022-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_documentlink_faq_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.TextField(),
        ),
    ]
