# Generated by Django 4.2.2 on 2023-06-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0005_remove_category_title_en_remove_category_title_ru_and_more'),
        ('mentors', '0008_mentor_email'),
        ('pages', '0002_remove_faq_answer_en_remove_faq_answer_ru_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageMentorSet',
            new_name='PageMentors',
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pages',
                to='tags.category',
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pages',
                to='tags.tag',
            ),
        ),
        migrations.AlterModelTable(
            name='pagementors',
            table='page_mentors',
        ),
    ]
