# Generated by Django 4.2.3 on 2023-07-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0003_alter_category_icon'),
        ('pages', '0003_alter_sociallink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tags.category',
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='tag',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tags.tag',
            ),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(),
        ),
    ]
