# Generated by Django 3.2.2 on 2022-02-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220212_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tag_set',
        ),
    ]
