# Generated by Django 4.2.2 on 2023-06-09 18:09

import django.db.models.deletion
from django.db import migrations, models


def copy_tag_set_to_tags(apps, _):
    Page = apps.get_model('pages', 'Page')
    for obj in Page.objects.all():
        obj.tags.set(obj.tag_set.all())


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0008_mentor_email'),
        ('tags', '0005_remove_category_title_en_remove_category_title_ru_and_more'),
        ('pages', '0003_rename_pagementorset_pagementors_alter_page_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='mentor_set',
        ),
        migrations.AddField(
            model_name='page',
            name='mentors',
            field=models.ManyToManyField(
                related_name='pages', through='pages.PageMentors', to='mentors.mentor'
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(related_name='pages_by_tags', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tag_set',
            field=models.ManyToManyField(
                related_name='pages_by_tag_set', to='tags.tag'
            ),
        ),
        migrations.AlterField(
            model_name='pagementors',
            name='mentor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='page_mentors',
                to='mentors.mentor',
            ),
        ),
        migrations.AlterField(
            model_name='pagementors',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='page_mentors',
                to='pages.page',
            ),
        ),
        migrations.RunPython(copy_tag_set_to_tags),
    ]
