# Generated by Django 4.2.2 on 2023-06-09 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0004_remove_page_mentor_set_page_mentors_page_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tag_set',
        ),
    ]
