# Generated by Django 4.2.2 on 2023-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0005_remove_page_tag_set'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagementors',
            constraint=models.UniqueConstraint(
                fields=('page', 'mentor'), name='unique_page_mentor'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagementors',
            constraint=models.UniqueConstraint(
                fields=('page', 'index'), name='unique_page_index'
            ),
        ),
    ]
