# Generated by Django 4.1.5 on 2023-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentlink',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='locale',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['pk']},
        ),
    ]
