# Generated by Django 3.2.2 on 2022-02-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='fields',
        ),
        migrations.AlterField(
            model_name='application',
            name='about',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='facebook',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='telegram',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='viber',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='whats_app',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    (
        'type',
        models.TextField(
            choices=[
                ('name', 'Имя'),
                ('email', 'Email'),
                ('telegram', 'Telegram'),
                ('facebook', 'Facebook messanger'),
                ('whats_app', 'WhatsApp'),
                ('viber', 'Viber'),
                ('about', 'О себе'),
            ]
        ),
    ),
    ('placeholder', models.TextField()),
    (
        'form',
        models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
    ),
],
            options={
                'unique_together': {('form', 'type')},
            },
        ),
    ]
