# Generated by Django 3.2.2 on 2022-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_auto_20220204_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_stopped',
            field=models.BooleanField(default=True),
        ),
    ]
