version: '3.9'

services:
  db:
    extends:
      file: docker/docker-compose.base.yml
      service: db
    ports: [ 5432:5432 ]
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    extends:
      file: docker/docker-compose.base.yml
      service: redis
  api:
    extends:
      file: docker/docker-compose.base.yml
      service: api
    build:
      context: .
    ports: [ 8000:8000 ]
    volumes:
      - profiles_volume:/api/profiles
      - media_volume:/api/media
    command: bash -c "
      python manage.py migrate
      && python manage.py collectstatic --noinput
      && daphne -b 0.0.0.0 -p 8000 api.asgi:application"
    depends_on: [ db, redis ]
  celery:
    extends:
      file: docker/docker-compose.base.yml
      service: celery
    build:
      context: .
    depends_on: [ api ]
  celery_beat:
    extends:
      file: docker/docker-compose.base.yml
      service: celery_beat
    build:
      context: .
    depends_on: [ celery ]

volumes:
  db_volume:
  profiles_volume:
  media_volume:

networks:
  db_network:
  redis_network:
