version: '3.9'

services:
  db:
    extends:
      file: docker/docker-compose.base.yml
      service: db
    image: postgres:15.3
    ports: [ 5433:5432 ]
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis:
    extends:
      file: docker/docker-compose.base.yml
      service: redis
    volumes:
      - redis_volume:/data

  api:
    extends:
      file: docker/docker-compose.base.yml
      service: api
    build:
      context: .
    ports: [ 8100:8000 ]
    networks: [ api_network, cal-api_network ]
    volumes:
      - media_volume:/api/media
      - static_volume:/api/static
    depends_on: [ db, redis ]

  celery:
    extends:
      file: docker/docker-compose.base.yml
      service: celery
    build:
      context: .
    depends_on: [ api ]

  cbeat:
    extends:
      file: docker/docker-compose.base.yml
      service: cbeat
    build:
      context: .
    depends_on: [ celery ]

  nginx:
    extends:
      file: docker/docker-compose.base.yml
      service: nginx
    build:
      dockerfile: local.dockerfile
    ports: [ 80:80, 443:443 ]
    networks: [ cal-web_network ]
    volumes:
      - static_volume:/etc/nginx/html/api/static
    depends_on: [ api ]

  cal-db:
    extends:
      file: docker/docker-compose.base.yml
      service: cal-db
    ports: [ 54321:5432 ]

  cal-web:
    extends:
      file: docker/docker-compose.base.yml
      service: cal-web
    depends_on: [ cal-db ]

  cal-api:
    extends:
      file: docker/docker-compose.base.yml
      service: cal-api
    ports: [ 3000:3000 ]
    depends_on: [ cal-db ]

  elasticsearch:
    extends:
      file: docker/docker-compose.base.yml
      service: elasticsearch

  logstash:
    extends:
      file: docker/docker-compose.base.yml
      service: logstash
    depends_on: [ elasticsearch ]

  kibana:
    extends:
      file: docker/docker-compose.base.yml
      service: kibana
    depends_on: [ elasticsearch ]

volumes:
  db_volume:
  redis_volume:
  media_volume:
  static_volume:
  nginx_logs_volume:
  cal-db_volume:
  elastic_volume:

networks:
  db_network:
  redis_network:
  api_network:
  cal-db_network:
  cal-web_network:
  cal-api_network:
  elastic_network:
