version: '3.8'

services:
  redis:
    image: redis:6.2.6
    networks:
      - redis_network

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/creaty/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.debug.env
    depends_on:
      - redis
    networks:
      - redis_network
    extra_hosts:
      - "host.docker.internal:172.18.0.3"

networks:
  redis_network:
