version: '3.9'

services:
  redis:
    image: redis:6.2.6
    networks:
      - redis_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn api.wsgi -c gunicorn_conf.py
    env_file:
      - ./.env
    volumes:
      - static_volume:/api/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - db_network
      - redis_network
      - nginx_network
  nginx:
    image: nginx:1.21.6
    depends_on:
      - api
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/api/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/api/certs
    networks:
      - nginx_network
  celery:
    build:
      context: .
    command: celery -A api worker -c 3 -P gevent -l info
    env_file:
      - ./.env
    depends_on:
      - nginx
    networks:
      - db_network
      - redis_network
  celery_beat:
    build:
      context: .
    command: celery -A api beat -S django -l info
    env_file:
      - ./.env
    depends_on:
      - celery
    networks:
      - db_network
      - redis_network

volumes:
  static_volume:

networks:
  db_network:
  redis_network:
  nginx_network:
