version: '3.9'

services:
  db:
    extends:
      file: docker/docker-compose.base.yml
      service: db
    image: postgres:15.3
    ports: [ 54320:5432 ]
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    extends:
      file: docker/docker-compose.base.yml
      service: redis
    volumes:
      - redis_volume:/data
  api:
    extends:
      file: docker/docker-compose.base.yml
      service: api
    build:
      context: .
    ports: [ 801:8000 ]
    volumes:
      - media_volume:/api/media
    command: bash -c "
      sleep 3
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && (daphne -b 0.0.0.0 -p 8001 api.asgi:application &)
      && gunicorn api.wsgi -c gunicorn/config.py
      "
    depends_on: [ db, redis ]
  celery:
    extends:
      file: docker/docker-compose.base.yml
      service: celery
    build:
      context: .
    depends_on: [ api ]
  celery_beat:
    extends:
      file: docker/docker-compose.base.yml
      service: celery_beat
    build:
      context: .
    depends_on: [ celery ]

volumes:
  db_volume:
  redis_volume:
  media_volume:

networks:
  db_network:
  redis_network:
