version: '3.9'

services:
  db:
    extends:
      file: docker/docker-compose.base.yml
      service: db
    image: postgres:15.3
    ports: [35432:5432]
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis-cache:
    extends:
      file: docker/docker-compose.base.yml
      service: redis-cache

  redis-cacheops:
    extends:
      file: docker/docker-compose.base.yml
      service: redis-cacheops

  redis-storage:
    extends:
      file: docker/docker-compose.base.yml
      service: redis-storage
    volumes:
      - redis-storage_volume:/data

  redis-celery:
    extends:
      file: docker/docker-compose.base.yml
      service: redis-celery
    volumes:
      - redis-celery_volume:/data

  api:
    extends:
      file: docker/docker-compose.base.yml
      service: api
    build:
      context: .
    ports: [38000:8000]
    networks: [api_network, cal-db_network, cal-api_network]
    volumes:
      - media_volume:/api/media
      - static_volume:/api/static
    depends_on: [db, redis-cache, redis-cacheops, redis-storage]

  celery:
    extends:
      file: docker/docker-compose.base.yml
      service: celery
    build:
      context: .
    depends_on: [api, redis-celery]

  cbeat:
    extends:
      file: docker/docker-compose.base.yml
      service: cbeat
    build:
      context: .
    depends_on: [celery]

  nginx:
    extends:
      file: docker/docker-compose.base.yml
      service: nginx
    build:
      dockerfile: local.dockerfile
    ports: [80:80, 443:443]
    networks: [cal_network]
    volumes:
      - static_volume:/etc/nginx/html/api/static
    depends_on: [api]

  cal-db:
    extends:
      file: docker/docker-compose.base.yml
      service: cal-db
    ports: [35433:5432]

  cal:
    extends:
      file: docker/docker-compose.base.yml
      service: cal
    domainname: cal.local.host
    depends_on: [cal-db]

#  cal-api:
#    extends:
#      file: docker/docker-compose.base.yml
#      service: cal-api
#    ports: [30000:3000]
#    depends_on: [cal-db]

volumes:
  db_volume:
  redis-cache_volume:
  redis-cacheops_volume:
  redis-storage_volume:
  redis-celery_volume:
  media_volume:
  static_volume:
  cal-db_volume:

networks:
  db_network:
  redis_network:
  api_network:
  cal-db_network:
  cal_network:
  cal-api_network:
