# Generated by Django 4.1.6 on 2023-02-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(),
        ),
    ]
