# Generated by Django 4.1.7 on 2023-05-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_user_has_discount_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
