# Generated by Django 4.1.7 on 2023-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
