version: '3.9'

services:
  zabbix-db:
    image: mysql:8.0.33
    container_name: zabbix-db
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf:ro
      - data:/var/lib/mysql
    networks: [ net ]

  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.4.1-ubuntu
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: root
      MYSQL_PASSWORD: zabbix
      ZBX_HOSTNAME: zabbix-server
    networks: [ net ]
    depends_on: [ zabbix-db ]

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.4.1-ubuntu
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: root
      MYSQL_PASSWORD: zabbix
    networks: [ net ]
    ports: [ 8080:8080 ]
    depends_on: [ zabbix-db, zabbix-server ]

  zabbix-agent:
    image: zabbix/zabbix-agent:6.4.1-ubuntu
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Zabbix server
    privileged: true
    pid: "host"
    ipc: "host"
    networks:
      net:
        aliases:
          - zabbix-agent
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
    depends_on: [ zabbix-server ]

volumes:
  data:

networks:
  net:
