# Generated by Django 3.2.2 on 2022-02-06 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0004_auto_20220202_1430'),
        ('tags', '0003_auto_20220206_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tags.category',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageTagSet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('index', models.IntegerField()),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='pages.page'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tags.tag'
                    ),
                ),
            ],
            options={
                'db_table': 'page_tag_set',
            },
        ),
        migrations.CreateModel(
            name='PageMentorSet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'index',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(19)]
                    ),
                ),
                (
                    'mentor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor'
                    ),
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='pages.page'
                    ),
                ),
            ],
            options={
                'db_table': 'page_mentor_set',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='mentor_set',
            field=models.ManyToManyField(
                through='pages.PageMentorSet', to='mentors.Mentor'
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tags.tag',
            ),
        ),
        migrations.AddField(
            model_name='page',
            name='tag_set',
            field=models.ManyToManyField(
                related_name='page_set_by_tag_set',
                through='pages.PageTagSet',
                to='tags.Tag',
            ),
        ),
        migrations.AddConstraint(
            model_name='pagetagset',
            constraint=models.UniqueConstraint(
                fields=('page', 'tag'), name='page_tag_set__unique__page__tag'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagetagset',
            constraint=models.UniqueConstraint(
                fields=('page', 'index'), name='page_tag_set__unique__page__index'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagementorset',
            constraint=models.UniqueConstraint(
                fields=('page', 'mentor'), name='page_mentor_set__unique__page__mentor'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagementorset',
            constraint=models.UniqueConstraint(
                fields=('page', 'index'), name='page_mentor_set__unique__page__index'
            ),
        ),
    ]
