# Generated by Django 3.2.2 on 2022-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    (
        'type',
        models.TextField(
            choices=[
                ('facebook', 'Facebook'),
                ('instagram', 'Instagram'),
                ('help', 'Написать в поддержку'),
                ('user_agreement', 'Пользовательское соглашение'),
                ('privacy_policy', 'Политика конфиденциальности'),
                ('cookie_policy', 'Cookie Policy'),
            ],
            unique=True,
        ),
    ),
    ('url', models.URLField()),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    ('question', models.TextField()),
    ('question_ru', models.TextField(null=True)),
    ('question_en', models.TextField(null=True)),
    ('answer', models.TextField()),
    ('answer_ru', models.TextField(null=True)),
    ('answer_en', models.TextField(null=True)),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    ('icon', models.ImageField(upload_to='pages/social_link/icon')),
    ('url', models.URLField()),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
