# Generated by Django 3.2.2 on 2022-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_category_icon'),
        ('pages', '0004_remove_page_tag_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tag_set',
            field=models.ManyToManyField(related_name='page_set_by_tag_set', to='tags.Tag'),
        ),
        migrations.DeleteModel(
            name='PageTagSet',
        ),
    ]
