# Generated by Django 3.2.2 on 2022-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220217_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(choices=[('ru', 'Русский'), ('en', 'Английский')], unique=True)),
                ('json', models.JSONField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
