# Generated by Django 4.1.5 on 2023-02-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('shortcut', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('title_ru', models.TextField(null=True)),
                ('title_en', models.TextField(null=True)),
                ('icon', models.ImageField(upload_to='tags/category/icon')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('shortcut', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('title_ru', models.TextField(null=True)),
                ('title_en', models.TextField(null=True)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tags.category'
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
