# Generated by Django 3.2.2 on 2022-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.TextField(null=True),
        ),
    ]
