# Generated by Django 4.1.7 on 2023-04-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tags.category'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tags.tag'
                    ),
                ),
            ],
            options={
                'unique_together': {('category', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(
                related_name='tags', through='tags.CategoryTag', to='tags.category'
            ),
        ),
    ]
