# Generated by Django 4.2.3 on 2023-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='category/icon'),
        ),
    ]
