# Generated by Django 4.1.7 on 2023-04-19 17:39

from django.db import migrations


def forwards(apps, _):
    Category = apps.get_model('tags', 'Category')
    CategoryTag = apps.get_model('tags', 'CategoryTag')

    for category in Category.objects.all():
        for tag in category.tag_set.all():
            CategoryTag.objects.create(category=category, tag=tag)


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0002_categorytag_tag_categories'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
