# Generated by Django 3.2.2 on 2022-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20220131_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shortcut',
            field=models.TextField(default='shortcut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='shortcut',
            field=models.TextField(default='shortcut'),
            preserve_default=False,
        ),
    ]
