# Generated by Django 4.2.3 on 2023-07-22 20:06

from django.db import migrations, models

import app.tags.models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to=app.tags.models.category_icon_upload_to),
        ),
    ]
