# Generated by Django 4.1.7 on 2023-04-19 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0003_auto_20230419_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
