# Generated by Django 3.2.2 on 2022-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20220206_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='_', upload_to='tags/category/icon'),
            preserve_default=False,
        ),
    ]
