# Generated by Django 4.1.5 on 2023-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['pk']},
        ),
    ]
