# Generated by Django 4.1.5 on 2023-02-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('become_mentor', 'Станьте ментором'),
                            ('choose_mentor', 'Получить помощь в подборе ментора'),
                            ('test_meeting', 'Беспатная тестовая встреча'),
                            ('still_questions', 'Ещё остались вопросы'),
                            ('signup_mentor', 'Записаться к ментору'),
                        ],
                        unique=True,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('post_send', models.TextField()),
                ('post_send_ru', models.TextField(null=True)),
                ('post_send_en', models.TextField(null=True)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('path', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('whats_app', models.TextField(blank=True)),
                ('viber', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forms.form'
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('name', 'Имя'),
                            ('email', 'Email'),
                            ('telegram', 'Telegram'),
                            ('facebook', 'Facebook messanger'),
                            ('whats_app', 'WhatsApp'),
                            ('viber', 'Viber'),
                            ('about', 'О вопросе'),
                        ]
                    ),
                ),
                ('placeholder', models.TextField()),
                ('placeholder_ru', models.TextField(null=True)),
                ('placeholder_en', models.TextField(null=True)),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forms.form'
                    ),
                ),
            ],
            options={
                'unique_together': {('form', 'type')},
            },
        ),
    ]
