# Generated by Django 4.2.2 on 2023-06-27 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('become_mentor', 'Become a mentor'),
                            ('choose_mentor', 'Get help choosing a mentor'),
                            ('test_meeting', 'Free test meeting'),
                            ('still_questions', 'Still have questions'),
                        ],
                        unique=True,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                ('post_send', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('path', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forms.form'
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('name', 'Name'),
                            ('email', 'Email'),
                            ('about', 'About the issue'),
                            ('link', 'Profile link'),
                        ]
                    ),
                ),
                ('placeholder', models.TextField()),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forms.form'
                    ),
                ),
            ],
            options={
                'unique_together': {('form', 'type')},
            },
        ),
    ]
