# Generated by Django 3.2.2 on 2022-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220208_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='placeholder_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='placeholder_ru',
            field=models.TextField(null=True),
        ),
    ]
