# Generated by Django 3.2.2 on 2022-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20220208_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.TextField(
                choices=[
                    ('name', 'Имя'),
                    ('email', 'Email'),
                    ('telegram', 'Telegram'),
                    ('facebook', 'Facebook messanger'),
                    ('whats_app', 'WhatsApp'),
                    ('viber', 'Viber'),
                    ('about', 'О вопросе'),
                ]
            ),
        ),
    ]
