# Generated by Django 4.2.2 on 2023-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0003_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.TextField(
                choices=[
                    ('name', 'Имя'),
                    ('email', 'Email'),
                    ('telegram', 'Telegram'),
                    ('facebook', 'Facebook messanger'),
                    ('whats_app', 'WhatsApp'),
                    ('viber', 'Viber'),
                    ('about', 'О вопросе'),
                    ('link', 'Ссылка на профиль'),
                ]
            ),
        ),
    ]
