# Generated by Django 3.2.2 on 2022-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
