# Generated by Django 3.2.2 on 2022-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_application_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='url',
        ),
        migrations.AddField(
            model_name='application',
            name='path',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
    ]
