# Generated by Django 4.2.2 on 2023-06-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0006_remove_application_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.TextField(
                choices=[
                    ('become_mentor', 'Become a mentor'),
                    ('choose_mentor', 'Get help choosing a mentor'),
                    ('test_meeting', 'Free test meeting'),
                    ('still_questions', 'Still have questions'),
                ],
                unique=True,
            ),
        ),
    ]
