# Generated by Django 4.1.5 on 2023-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_form_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['pk']},
        ),
    ]
