version: '3.9'

services:
  db:
    container_name: db
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: db
    env_file: [ ../envs/.base.env ]
    networks: [ db_network ]
    restart: unless-stopped

  redis:
    container_name: redis
    build:
      context: ../redis
    env_file: [ ../envs/.base.env ]
    networks: [ redis_network ]
    restart: unless-stopped

  api:
    container_name: api
    command: bash -c "
      python manage.py migrate
      && python manage.py collectstatic --noinput
      && (daphne -b 0.0.0.0 -p 8001 api.asgi:application &)
      && gunicorn api.wsgi -c gunicorn/config.py
      "
    env_file: [ ../envs/.base.env ]
    networks: [ db_network, redis_network ]
    restart: unless-stopped

  celery:
    container_name: celery
    extends:
      service: api
    command: bash -c "
      sleep 10
      && celery -A api worker -c 2 -P gevent -l info
      "

  cbeat:
    container_name: cbeat
    extends:
      service: api
    command: bash -c "
      sleep 10
      && celery -A api beat -S django -l info
      "

  nginx:
    container_name: nginx
    build:
      context: ../nginx
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .conf
    env_file: [ ../envs/.base.env ]
    volumes:
      - nginx_logs_volume:/var/log/nginx
    networks: [ api_network ]
    restart: unless-stopped

  cal-db:
    container_name: cal-db
    image: postgres:15.3
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: password
    volumes:
      - cal-db_volume:/var/lib/postgresql/data/
    networks: [ cal-db_network ]
    restart: unless-stopped

  cal-web:
    container_name: cal-web
    image: calcom/cal.com:v3.1.5
    env_file: [ ../envs/.base.env ]
    environment:
      DATABASE_URL: postgresql://pg:password@cal-db:5432/db
      NEXT_PUBLIC_LICENSE_CONSENT: agree
      LICENSE: agree
    networks: [ cal-db_network, cal-web_network ]
    restart: unless-stopped

  cal-api:
    container_name: cal-api
    image: calcom/cal.com:v3.1.5
    env_file: [ ../envs/.base.env ]
    environment:
      DATABASE_URL: postgresql://pg:password@cal-db:5432/db
      NEXT_PUBLIC_WEBAPP_URL: http://cal-api:3000
      NEXT_AUTH_URL: http://cal-api:3000/api/auth
      NEXT_PUBLIC_LICENSE_CONSENT: agree
      LICENSE: agree
    networks: [ cal-db_network, cal-api_network ]
    restart: unless-stopped

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      ELASTIC_PASSWORD: password
      node.name: elasticsearch
      discovery.type: single-node
      xpack.security.http.ssl.enabled: false
      xpack.security.enabled: false
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    networks: [ elastic_network ]

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.9.0
    volumes:
      - nginx_logs_volume:/var/log/nginx
      - ../logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks: [ elastic_network ]

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_PASSWORD: password
    networks: [ elastic_network ]
    ports:
      - 5601:5601

volumes:
  db_volume:
  redis_volume:
  media_volume:
  api_static_volume:
  nginx_logs_volume:
  cal-db_volume:

networks:
  db_network:
  redis_network:
  api_network:
  cal-db_network:
  cal-web_network:
  cal-api_network:
  elastic_network:
