version: '3.9'

services:
  db:
    container_name: db
    env_file: [ ../envs/.base.env ]
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_DB=db
    networks: [ db_network ]
    restart: unless-stopped

  redis:
    container_name: redis
    build:
      context: ../redis
    env_file: [ ../envs/.base.env ]
    networks: [ redis_network ]
    restart: unless-stopped

  api:
    container_name: api
    env_file: [ ../envs/.base.env ]
    networks: [ db_network, redis_network ]
    restart: unless-stopped

  celery:
    container_name: celery
    extends:
      service: api
    env_file: [ ../envs/.base.env ]
    command: celery -A api worker -c 2 -P gevent -l info
    restart: unless-stopped

  celery_beat:
    container_name: celery_beat
    extends:
      service: api
    env_file: [ ../envs/.base.env ]
    command: celery -A api beat -S django -l info
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ../nginx
    env_file: [ ../envs/.base.env ]
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
    networks: [ nginx_network ]
    restart: unless-stopped
