# Generated by Django 4.1.5 on 2023-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=2, unique=True)),
                ('flag_unicode', models.CharField(max_length=11, unique=True)),
                ('name', models.TextField()),
                ('name_ru', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.TextField()),
                ('name_ru', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
                ('name_native', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
