# Generated by Django 4.1.5 on 2023-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['pk']},
        ),
    ]
