version: '3.9'

services:
  db:
    extends:
      file: ../docker-compose.base.yml
      service: db
    env_file: [ ../../envs/.prod.env ]
    ports: [ 5432:5432 ]
    volumes:
      - /home/www/creaty/db:/var/lib/postgresql/data
  redis:
    extends:
      file: ../docker-compose.base.yml
      service: redis
    env_file: [ ../../envs/.prod.env ]
  api:
    extends:
      file: ../docker-compose.base.yml
      service: api
    image: ${API_IMAGE}:${TAG}
    env_file: [ ../../envs/.prod.env ]
    volumes:
      - /home/www/creaty/media:/api/media
      - api_static_volume:/api/static
    command: bash -c "
      python manage.py collectstatic --noinput
      && (daphne -b 0.0.0.0 -p 8001 api.asgi:application &)
      && gunicorn api.wsgi -c gunicorn/config.py
      "
    networks: [ nginx_network ]
    depends_on: [ db, redis ]
  celery:
    extends:
      file: ../docker-compose.base.yml
      service: celery
    image: ${API_IMAGE}:${TAG}
    env_file: [ ../../envs/.prod.env ]
    depends_on: [ api ]
  celery_beat:
    extends:
      file: ../docker-compose.base.yml
      service: celery_beat
    image: ${API_IMAGE}:${TAG}
    env_file: [ ../../envs/.prod.env ]
    depends_on: [ celery ]
  nginx:
    extends:
      file: ../docker-compose.base.yml
      service: nginx
    build:
      dockerfile: ../nginx/prod.dockerfile
      args: [ TAG ]
    env_file: [ ../../envs/.prod.env ]
    ports: [ 443:443 ]
    volumes:
      - /home/www/creaty/media:/etc/nginx/html/api/media
      - api_static_volume:/etc/nginx/html/api/static
    depends_on: [ api ]

volumes:
  api_static_volume:

networks:
  db_network:
  redis_network:
  nginx_network:
