version: '3.9'

services:
  db:
    extends:
      file: ../docker-compose.base.yml
      service: db
    build:
      context: ../../db
    env_file: [ ../../envs/.prod.env ]
    ports: [ 5432:5432 ]
    volumes:
      - /home/www/creaty/db:/var/lib/postgresql/data
      - ../../db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  redis:
    extends:
      file: ../docker-compose.base.yml
      service: redis
    env_file: [ ../../envs/.prod.env ]

  api:
    extends:
      file: ../docker-compose.base.yml
      service: api
    image: ${API_IMAGE}:${TAG}
    env_file: [ ../../envs/.prod.env ]
    volumes:
      - static_volume:/api/static
    networks: [ api_network ]
    depends_on: [ db, redis ]

  celery:
    extends:
      file: ../docker-compose.base.yml
      service: celery
    image: ${API_IMAGE}:${TAG}
    env_file: [ ../../envs/.prod.env ]
    command: bash -c "
      sleep 10
      && celery -A api worker -c 4 -P gevent -l info
      "
    depends_on: [ api ]

  cbeat:
    extends:
      file: ../docker-compose.base.yml
      service: cbeat
    image: ${API_IMAGE}:${TAG}
    env_file: [ ../../envs/.prod.env ]
    depends_on: [ celery ]

  nginx:
    extends:
      file: ../docker-compose.base.yml
      service: nginx
    build:
      dockerfile: ../nginx/prod.dockerfile
      args: [ TAG ]
    env_file: [ ../../envs/.prod.env ]
    ports: [ 80:80, 443:443 ]
    volumes:
      - static_volume:/etc/nginx/html/api/static
    depends_on: [ api ]

volumes:
  static_volume:

networks:
  db_network:
  redis_network:
  api_network:
