# Generated by Django 3.2.2 on 2022-01-31 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    ('avatar', models.ImageField(upload_to='avatars')),
    ('company', models.TextField(blank=True, null=True)),
    ('profession', models.TextField(blank=True, null=True)),
    ('first_name', models.TextField()),
    ('last_name', models.TextField()),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorInfo',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    (
        'trial_meeting',
        models.SmallIntegerField(
            blank=True,
            null=True,
            validators=[django.core.validators.MinValueValidator(1)],
        ),
    ),
    ('resume', models.TextField()),
    ('what_help', models.TextField()),
    ('experience', models.TextField()),
    ('portfolio', models.TextField()),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    (
        'lessons_count',
        models.SmallIntegerField(
            validators=[django.core.validators.MinValueValidator(2)]
        ),
    ),
    (
        'discount',
        models.SmallIntegerField(
            validators=[
                django.core.validators.MinValueValidator(1),
                django.core.validators.MaxValueValidator(99),
            ]
        ),
    ),
    (
        'mentor',
        models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor'
        ),
    ),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='info',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='mentors.mentorinfo'
            ),
        ),
    ]
