# Generated by Django 3.2.2 on 2022-02-01 18:23

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='money',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1'), max_digits=10),
        ),
        migrations.AddField(
            model_name='mentor',
            name='money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
    ]
