# Generated by Django 3.2.2 on 2022-02-02 11:30

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_language_code'),
        ('tags', '0002_auto_20220131_1808'),
        ('mentors', '0003_alter_mentor_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='money',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='money_currency',
        ),
        migrations.AddField(
            model_name='mentor',
            name='country',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='geo.country'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('EUR', 'EUR €'), ('RUB', 'RUB ₽'), ('USD', 'USD $')],
                default='USD',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name='mentor',
            name='tag_set',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='city',
            field=models.TextField(default='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='city_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='city_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='language_set',
            field=models.ManyToManyField(to='geo.Language'),
        ),
    ]
