# Generated by Django 3.2.2 on 2022-02-04 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
    (
        'id',
        models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name='ID',
        ),
    ),
    ('subject', models.TextField()),
    ('content', models.TextField()),
    (
        'task_ids',
        django.contrib.postgres.fields.ArrayField(
            base_field=models.TextField(), blank=True, null=True, size=None
        ),
    ),
],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscriber',
        ),
    ]
