# Generated by Django 3.2.2 on 2022-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('mailings', '0005_auto_20220313_1115'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
