# Generated by Django 3.2.2 on 2022-04-03 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_auto_20220313_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
