# Generated by Django 3.2.2 on 2022-02-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
