# Generated by Django 4.1.5 on 2023-02-01 08:03

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('slug', models.SlugField(unique=True)),
                (
                    'avatar',
                    models.ImageField(blank=True, null=True, upload_to='avatars'),
                ),
                ('company', models.TextField(blank=True, null=True)),
                ('profession', models.TextField()),
                ('profession_ru', models.TextField(null=True)),
                ('profession_en', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('first_name_ru', models.TextField(null=True)),
                ('first_name_en', models.TextField(null=True)),
                ('last_name', models.TextField()),
                ('last_name_ru', models.TextField(null=True)),
                ('last_name_en', models.TextField(null=True)),
                (
                    'price_currency',
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ('USD', 'Доллар США ($)'),
                            ('EUR', 'Евро (€)'),
                            ('RUB', 'Рубль (₽)'),
                        ],
                        default='USD',
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    'price',
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
                ),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='geo.country'
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'lessons_count',
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(2)]
                    ),
                ),
                (
                    'discount',
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                (
                    'mentor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='packages',
                        to='mentors.mentor',
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorInfo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'trial_meeting',
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('resume', models.TextField()),
                ('resume_ru', models.TextField(null=True)),
                ('resume_en', models.TextField(null=True)),
                ('what_help', models.TextField(blank=True, null=True)),
                ('what_help_ru', models.TextField(blank=True, null=True)),
                ('what_help_en', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('experience_ru', models.TextField(blank=True, null=True)),
                ('experience_en', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('language_set', models.ManyToManyField(to='geo.language')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='info',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='mentors.mentorinfo'
            ),
        ),
        migrations.AddField(
            model_name='mentor',
            name='tag_set',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
