# Generated by Django 4.2.2 on 2023-06-27 10:32

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models

import app.users.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                (
                    'user_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('slug', models.SlugField(unique=True)),
                (
                    'avatar',
                    models.ImageField(blank=True, null=True, upload_to='avatars'),
                ),
                ('company', models.TextField(blank=True, default='')),
                ('profession', models.TextField()),
                (
                    'price_currency',
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ('USD', 'Доллар США ($)'),
                            ('EUR', 'Евро (€)'),
                            ('RUB', 'Рубль (₽)'),
                        ],
                        default='USD',
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    'price',
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
                ),
                ('is_draft', models.BooleanField(default=True)),
                (
                    'trial_meeting',
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('resume', models.TextField()),
                ('what_help', models.TextField(blank=True, default='')),
                ('experience', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='mentors',
                        to='geo.country',
                    ),
                ),
                (
                    'languages',
                    models.ManyToManyField(related_name='mentors', to='geo.language'),
                ),
                ('tags', models.ManyToManyField(related_name='mentors', to='tags.tag')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', app.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'lessons_count',
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(2)]
                    ),
                ),
                (
                    'discount',
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                (
                    'mentor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='packages',
                        to='mentors.mentor',
                    ),
                ),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
