# Generated by Django 4.1.7 on 2023-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
