# Generated by Django 4.2.3 on 2023-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='avatar',
        ),
    ]
