# Generated by Django 4.2.2 on 2023-06-08 12:55

import django.core.validators
from django.db import migrations, models


def move_info_to_mentor(apps, _):
    Mentor = apps.get_model('mentors', 'Mentor')
    for mentor in Mentor.objects.all():
        mentor.trial_meeting = mentor.info.trial_meeting
        mentor.resume = mentor.info.resume
        mentor.what_help = mentor.info.what_help or ''
        mentor.experience = mentor.info.experience or ''
        mentor.city = mentor.info.city or ''
        mentor.languages.set(mentor.info.language_set.all())
        mentor.save()


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0002_remove_country_name_en_remove_country_name_ru_and_more'),
        ('mentors', '0003_remove_mentor_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='city',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mentor',
            name='languages',
            field=models.ManyToManyField(to='geo.language'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='resume',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='trial_meeting',
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name='mentor',
            name='what_help',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='company',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(move_info_to_mentor),
    ]
