# Generated by Django 3.2.2 on 2022-02-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_auto_20220202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='mentor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='packages',
                to='mentors.mentor',
            ),
        ),
    ]
