# Generated by Django 4.2.2 on 2023-06-08 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0004_mentor_city_mentor_experience_mentor_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='info',
        ),
        migrations.DeleteModel(
            name='MentorInfo',
        ),
    ]
