# Generated by Django 3.2.2 on 2022-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20220221_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorinfo',
            name='experience_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='experience_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='portfolio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='portfolio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='resume_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='resume_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='what_help_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='what_help_ru',
            field=models.TextField(null=True),
        ),
    ]
