# Generated by Django 4.2.2 on 2023-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0007_remove_mentor_tag_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
