# Generated by Django 4.2.2 on 2023-06-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0008_mentor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(
                blank=True, db_index=True, default='', max_length=254
            ),
        ),
    ]
