# Generated by Django 4.1.5 on 2023-01-22 17:00

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_auto_20220727_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='mentorinfo',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='mentor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('USD', 'Доллар США ($)'),
                    ('EUR', 'Евро (€)'),
                    ('RUB', 'Рубль (₽)'),
                ],
                default='USD',
                editable=False,
                max_length=3,
            ),
        ),
    ]
