# Generated by Django 4.1.5 on 2023-01-22 17:03

from django.db import migrations
from uuslug import uuslug


def re_save_mentors(apps, _):
    Mentor = apps.get_model('mentors', 'Mentor')
    for mentor in Mentor.objects.all():
        mentor.slug = uuslug(f"{mentor.first_name}_{mentor.last_name}", mentor)
        mentor.save()


def reverse(*_):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_alter_mentor_options_alter_mentorinfo_options_and_more'),
    ]

    operations = [migrations.RunPython(re_save_mentors, reverse)]
