# Generated by Django 4.1.5 on 2023-01-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_auto_20230122_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='slug',
            field=models.SlugField(default='-', unique=True),
            preserve_default=False,
        ),
    ]
