# Generated by Django 4.2.2 on 2023-06-21 18:35
import django
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
from django.utils.crypto import get_random_string

import app.users.managers


def create_users_from_mentors(apps, _):
    Mentor = apps.get_model('mentors', 'Mentor')
    User = apps.get_model('users', 'User')
    for mentor in Mentor.objects.all():
        try:
            user = User.objects.get(email=mentor.email)
        except User.DoesNotExist:
            user = User(email=mentor.email)
            user.password = make_password(get_random_string(16))
        user.first_name = mentor.first_name
        user.last_name = mentor.last_name
        user.save()
        mentor.user_ptr = user
        mentor.save()


class Migration(migrations.Migration):
    dependencies = [
        ('mentors', '0010_alter_mentor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='user_ptr',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(create_users_from_mentors),
        migrations.AlterModelManagers(
            name='mentor',
            managers=[
                ('objects', app.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
