# Generated by Django 4.1.5 on 2023-01-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_alter_mentor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorinfo',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='mentorinfo',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='mentorinfo',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='mentorinfo',
            name='portfolio_en',
        ),
        migrations.RemoveField(
            model_name='mentorinfo',
            name='portfolio_ru',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profession',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profession_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profession_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='experience_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='experience_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='what_help',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='what_help_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='what_help_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
