# Generated by Django 4.1.5 on 2023-01-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'mentors',
            '0012_remove_mentorinfo_city_en_remove_mentorinfo_city_ru_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(default='-', upload_to='avatars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profession_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profession_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
