# Generated by Django 4.1.5 on 2023-01-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'mentors',
            '0012_remove_mentorinfo_city_en_remove_mentorinfo_city_ru_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorinfo',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
