name: "Call: deploy stage"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  bw:
    uses: ./.github/workflows/call-bw.yml
    with:
      secret_name: API_STAGE_ENV
    secrets: inherit
  deploy:
    runs-on: self-hosted
    needs: bw
    environment:
      name: stage
      url: 'http://stage.creaty.club'
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          clean: false
      - name: Set stage envs
        run: |
          secret=$(echo "${{ needs.bw.outputs.secret_value }}" |
            openssl enc -aes-256-cbc -d -a -k "${{ secrets.BW_CREDENTIALS }}" -pbkdf2
          )
          echo "$secret" > envs/.stage.env
          echo "SENTRY_RELEASE=${{ github.sha }}" >> envs/.stage.env
      - name: Pull api docker image
        run: docker-compose -f docker/stage/docker-compose.stage.yml pull api
      - name: Pull web docker image
        run: docker pull ghcr.io/creaty-co/creaty-web/web:latest
      - name: Deploy stage environment
        run: docker-compose -f docker/stage/docker-compose.stage.yml up --build -d
