on:
  workflow_call:
    outputs:
      envs:
        value: ${{ jobs.envs.outputs.envs }}

jobs:
  envs:
    runs-on: ubuntu-22.04
    environment:
      name: dev
    steps:
      - run: |
          env_keys=("TEST_VAR" "TEST_VAR2")
          vars_json='${{ toJSON(vars) }}'
          envs=''
          for env_key in "${env_keys[@]}"; do
            env_var=$(echo $vars_json | jq -r --arg env_key "$env_key" '.[$env_key]')
            envs=$envs$env_key=$env_var\\n
          done
          echo envs=$envs >> $GITHUB_OUTPUT
