name: "Call: CI"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.10.8
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run tests
        run: |
          docker-compose -f docker/test/docker-compose.yml up --build \
          --exit-code-from api --abort-on-container-exit api
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverages/coverage.xml
