on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      env_keys:
        type: string
        required: false
        default: '
          WEB_DOMAIN,
          API_DOMAIN
        '
    outputs:
      envs:
        value: ${{ jobs.envs.outputs.envs }}

jobs:
  envs:
    runs-on: ubuntu-22.04
    outputs:
      envs: ${{ steps.envs.outputs.envs }}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - id: envs
        run: |
          env_keys=${{ inputs.env_keys }}
          IFS=',' read -ra env_keys <<< "${env_keys// /}"
          vars_json='${{ toJSON(vars) }}'
          secrets_json='${{ toJSON(secrets) }}'
          envs_json=$(jq -s '.[0] * .[1]' <(echo $vars_json) <(echo $secrets_json))
          envs=''
          for env_key in "${env_keys[@]}"; do
            env_var=$(echo $envs_json | jq -r --arg env_key "$env_key" '.[$env_key]')
            if [ "$env_var" == "null" ]; then
              echo "::error::KeyError: $env_key"
              exit 1
            fi
            envs=$envs$env_key=$env_var\\n
          done
          echo envs=$envs >> $GITHUB_OUTPUT
