name: "Call: deploy stage"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  deploy:
    runs-on: [ self-hosted, stage ]
    environment:
      name: stage
      url: 'https://stage.creaty.club'
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          clean: false
      - name: Set stage envs
        run: |
          export BW_SESSION=$(bw login ${{ secrets.BW_CREDENTIALS }} --raw)
          env=$(bw get item API_STAGE_ENV | jq .notes | tr -d '"')
          echo -e "$env" > envs/.stage.env
          echo "SENTRY_RELEASE=${{ inputs.tag }}" >> envs/.stage.env
          bw logout
      - name: Pull images
        run: |
          export TAG=${{ inputs.tag }}
          docker-compose -f docker/dev/docker-compose.yml pull api
          docker pull ghcr.io/creaty-co/creaty-web/web:${{ inputs.tag }}
      - name: Deploy stage environment
        run: |
          export TAG=${{ inputs.tag }}
          docker-compose -f docker/stage/docker-compose.yml up --build -d
