on:
  workflow_call:
    outputs:
      envs:
        value: ${{ jobs.get_envs.outputs.envs }}

jobs:
  get_envs:
    runs-on: ubuntu-22.04
    environment:
      name: dev
    env:
      ENVS: ''
    steps:
      - run: |
          env_keys=("TEST_VAR" "TEST_VAR2")
          vars_json='${{ toJSON(vars) }}'
          for env_key in "${env_keys[@]}"; do
            echo $env_key
            env_var=$(echo $vars_json | jq -r --arg env_key "$env_key" '.[$env_key]')
            echo $env_var
            envs=$ENVS$env_key=$env_var\\n
            echo ENVS=$envs >> $GITHUB_ENV
            echo $ENVS
          done
      - name: Set output
        run: echo envs=${{ env.ENVS }} >> $GITHUB_OUTPUT
