name: "Call: Sentry ralease"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      version:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      version:
        type: string
        required: false

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      - name: Create Sentry release
        uses: getsentry/action-release@v1.3.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: creaty-co
          SENTRY_PROJECT: creaty-api
        with:
          ignore_empty: true
          environment: ${{ inputs.environment }}
          version: ${{ inputs.version }}
