name: "Call: Sentry release"

on:
  workflow_call:
    inputs:
      environment:
        type: string
      version:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      environment:
        type: string
      version:
        type: string

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - id: get_commit_title
        uses: ./.github/workflows/call-get_commit_title.yml
      - name: Determine version
        run: |
          version=${{ inputs.version }}
          if [ -z "$version" ]; then
            version=${{ steps.get_commit_title.outputs.title }}
          fi
          echo "version=$version" >> $GITHUB_ENV
      - name: Create Sentry release
        uses: getsentry/action-release@v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: creaty-co
          SENTRY_PROJECT: creaty-api
        with:
          ignore_empty: true
          environment: ${{ inputs.environment }}
          version: ${{ env.version }}
