on:
  workflow_call:
    outputs:
      envs:
        value: ${{ jobs.get_envs.outputs.envs }}

jobs:
  get_envs:
    runs-on: ubuntu-22.04
    environment:
      name: dev
    env:
      ENVS: ''
    strategy:
      matrix:
        env_key: [ TEST_VAR, TEST_VAR2 ]
    steps:
      - run: |
          vars_json='${{ toJSON(vars) }}'
          env_var=$(echo $vars_json | jq -r '.${{ matrix.env_key }}')
          envs='{{ env.ENVS }}\n${{ matrix.env_key }}=$env_var'
          echo ENVS=$envs >> $GITHUB_ENV
      - name: Set output
        run: echo envs=${{ env.ENVS }} >> $GITHUB_OUTPUT
