name: "Call: BW"

on:
  workflow_call:
    inputs:
      secret_name:
        type: string
        required: true
    secrets:
      BW_CREDENTIALS:
        required: true
    outputs:
      secret_value:
        value: ${{ jobs.extract_secret.outputs.value }}

jobs:
  extract_secret:
    runs-on: ubuntu-22.04
    outputs:
      secret_value: ${{ steps.extract_secret_value.outputs.secret_value }}
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.13.0
      - name: Install bw cli
        run: npm install -g @bitwarden/cli
      - name: Authorization in bw
        run: |
          BW_SESSION=$(bw login ${{ secrets.BW_CREDENTIALS }} --raw)
          echo "BW_SESSION=$BW_SESSION" >> $GITHUB_ENV
      - name: Extract secret value
        id: extract_secret_value
        run: |
          secret_value=$(bw get item ${{ inputs.secret_name }} | jq .notes | tr -d '"')
          echo "secret_value=$secret_value" >> $GITHUB_OUTPUT
