name: "Call: Sentry release"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: 'dev'
      url:
        type: string
        required: true
      version:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: false
        default: 'dev'
      url:
        type: string
        required: true
      version:
        type: string

jobs:
  get_commit_title:
    uses: ./.github/workflows/call-get_commit_title.yml
  release:
    runs-on: ubuntu-22.04
    needs: [get_commit_title]
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Determine version
        # language="shell script"
        run: |
          version="${{ inputs.version }}"
          if [ -z "$version" ]; then
            version=${{ needs.get_commit_title.outputs.title }}
          fi
          echo "version=$version" >> $GITHUB_ENV
      - name: Create Sentry release
        uses: getsentry/action-release@v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: creaty-co
          SENTRY_PROJECT: creaty-api
        with:
          ignore_empty: true
          ignore_missing: true
          environment: ${{ inputs.environment }}
          version: ${{ env.version }}
        continue-on-error: true
