name: "Call: update PRs"

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-22.04
    if: always() || failure()
    steps:
      - uses: chinthakagodawita/autoupdate-action@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GENTLEENVY_TOKEN }}
          MERGE_MSG: "auto-update"
          MERGE_CONFLICT_ACTION: ignore
