name: "Call: deploy dev"

on:
  workflow_call:

jobs:
  envs:
    uses: ./.github/workflows/call-envs.yml
    secrets: inherit
  deploy:
    runs-on: ubuntu-22.04
    needs: [ envs ]
    steps:
      - name: Set dev envs
        run: |
          echo ${{ needs }}
          echo ${{ needs.envs }}
          echo ${{ needs.envs.outputs }}
          echo ${{ needs.envs.outputs.envs }}
          echo ${{ needs.envs.outputs.envs }} > .env
          cat .env
