on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      env_keys:
        type: string
        required: false
        default: '
          WEB_DOMAIN,
          API_DOMAIN,
          DEBUG,
          TEST,
          ANON_THROTTLE_RATE,
          USE_BROWSABLE_API,
          EMAIL_BACKEND,
          CELERY_TASK_EAGER,
          CELERY_REDIS_MAX_CONNECTIONS,
          CELERY_BROKER_POOL_LIMIT,
          CLOUDINARY_PREFIX,
          USE_SILK,
          SENTRY_ENVIRONMENT,
          REDIRECT_ON_UNSUBSCRIBE,
          ADMINS,
          LOG_PRETTY,
          LOG_REQUESTS,
          LOG_LEVEL
        '
    outputs:
      envs:
        value: ${{ jobs.envs.outputs.envs }}

jobs:
  envs:
    runs-on: ubuntu-22.04
    outputs:
      envs: ${{ steps.envs.outputs.envs }}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - id: envs
        run: |
          env_keys="${{ inputs.env_keys }}"
          IFS=',' read -ra env_keys <<< "${env_keys// /}"
          envs_json='${{ toJSON(vars) }}'
          envs=''
          for env_key in "${env_keys[@]}"; do
            env_var=$(echo $envs_json | jq -r --arg env_key "$env_key" '.[$env_key]')
            echo "$env_key=$env_var"
            if [ "$env_var" != "null" ]; then
              echo $env_key=$env_var
              envs=$envs$env_key=$env_var\\n
              echo $envs
            fi
          done
          echo envs=$envs >> $GITHUB_OUTPUT
