name: "Call: deploy dev"

on:
  workflow_call:

jobs:
  envs:
    uses: ./.github/workflows/call-envs.yml
    with:
      environment: dev
    secrets: inherit
  deploy:
    runs-on: ubuntu-22.04
    needs: [ envs ]
    steps:
      - name: Set .env file
        run: |
          echo -e "${{ needs.envs.outputs.envs }}" > .env
          secrets=(
            "SECRET_KEY"
            "EMAIL_URL"
            "SENTRY_DSN"
            "POSTGRES_PASSWORD"
            "DATABASE_URL"
            "GOOGLE_APP_ID"
            "GOOGLE_APP_SECRET"
            "FIXER_ACCESS_KEY"
          )
          for secret in ${secrets[@]}; do
            value=$(echo "${{ secrets[$secret] }}")
            if [[ -z "$value" ]]; then
              echo "$secret is not defined"
              exit 1
            fi
            echo "$secret=$value" >> .env
          done
          cat .env
