name: "Call: deploy stage"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: stage
      url: 'http://stage.creaty.club'
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          clean: false
      - name: Set stage envs
        run: |
          export BW_SESSION=$(bw login ${{ secrets.BW_CREDENTIALS }} --raw)
          env=$(bw get item API_STAGE_ENV | jq .notes | tr -d '"')
          echo "$env" > envs/.stage.env
          echo "SENTRY_RELEASE=${{ github.sha }}" >> envs/.stage.env
          bw logout
      - name: Pull api docker image
        run: docker-compose -f docker/stage/docker-compose.stage.yml pull api
      - name: Pull web docker image
        run: docker pull ghcr.io/creaty-co/creaty-web/web:latest
      - name: Deploy stage environment
        run: docker-compose -f docker/stage/docker-compose.stage.yml up --build -d
