name: "Call: deploy dev"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      url:
        type: string
        required: true
      sentry_release:
        type: string
        required: false
        default: "${{ github.sha }}"
      tag:
        type: string
        required: false
        default: 'latest'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      sentry_release:
        type: string
        required: false
      tag:
        type: string
        required: false
        default: 'latest'

jobs:
  envs:
    uses: ./.github/workflows/call-envs.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  deploy:
    runs-on: [ self-hosted, "${{ inputs.environment }}" ]
    needs: [ envs ]
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - name: Set .env file
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_URL: ${{ secrets.EMAIL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
          GOOGLE_APP_SECRET: ${{ secrets.GOOGLE_APP_SECRET }}
          FIXER_ACCESS_KEY: ${{ secrets.FIXER_ACCESS_KEY }}
        run: |
          env_filename=envs/.${{ inputs.environment }}.env
          echo -e "${{ needs.envs.outputs.envs }}" > $env_filename
          secrets=(
            "SECRET_KEY"
            "EMAIL_URL"
            "SENTRY_DSN"
            "POSTGRES_PASSWORD"
            "DATABASE_URL"
            "GOOGLE_APP_ID"
            "GOOGLE_APP_SECRET"
            "FIXER_ACCESS_KEY"
          )
          for secret in ${secrets[@]}; do
            value=$(echo "${!secret}")
            if [[ -z "$value" ]]; then
              echo "$secret is not defined"
              exit 1
            fi
            echo "$secret=$value" >> $env_filename
          done
          if [[ -n "${{ inputs.SENTRY_RELEASE }}" ]]; then
            echo "SENTRY_RELEASE=${{ inputs.SENTRY_RELEASE }}" >> $env_filename
          fi
      - uses: actions/checkout@v3.5.3
        with:
          clean: false
      - name: Pull images
        run: |
          export TAG=${{ inputs.tag }}
          docker-compose -f docker/${{ inputs.environment }}/docker-compose.yml pull api
          docker pull ghcr.io/creaty-co/creaty-web/web:${{ inputs.tag }}
      - name: Up docker compose
        run: |
          docker-compose -f docker/${{ inputs.environment }}/docker-compose.yml up \
          --build -d
