name: "Call: update version"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          repository: creaty-co/creaty-chart
          ssh-key: ${{ secrets.CHART_DEPLOY_KEY }}
          ref: envy

      - name: Update values.yaml
        # language="shell script"
        run: |
          git branch
          ls
          sed -i '
            0,/api_version: .*/s//api_version: ${{ inputs.version }}/
          ' environments/envy/values.yaml

      - name: Commit and push changes
        # language="shell script"
        run: |
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add environments/envy/values.yaml
          git commit -m "Update API version to ${{ inputs.version }}"
          git push
