name: "Call: get commit title"

on:
  workflow_call:
    inputs:
      sha:
        type: string
        required: false
    outputs:
      title:
        value: ${{ jobs.get_title.outputs.

jobs:
  get_title:
    runs-on: ubuntu-22.04
    outputs:
      title: ${{ steps.extract_title.outputs.title }}
    steps:
      - name: Extract title
        id: extract_title
        run: |
          sha=${{ inputs.sha }}
          if [ -z "$sha" ]; then
            sha=${{ github.sha }}
          fi
          title=$(git log --format=%s -n 1 $sha)
          echo "title=$title" >> $GITHUB_OUTPUT
