name: "Call: deploy"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      url:
        type: string
        required: true
      tag:
        type: string
        required: false
        default: 'latest'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      tag:
        type: string
        required: false
        default: 'latest'

jobs:
  get_commit_title:
    uses: ./.github/workflows/call-get_commit_title.yml
  deploy:
    runs-on: [ self-hosted, "${{ inputs.environment }}" ]
    needs: [ get_commit_title ]
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    env:
      env_filename: envs/.${{ inputs.environment }}.env
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set certs
        run: |
          mkdir -p nginx/certs
          echo -e "${{ vars.NGINX_SSL_CRT }}" > nginx/certs/crt.pem
          echo -e "${{ secrets.NGINX_SSL_KEY }}" > nginx/certs/key.pem
          mkdir -p db/certs
          echo -e "${{ vars.DB_SSL_CRT }}" > db/certs/crt.pem
          echo -e "${{ secrets.DB_SSL_KEY }}" > db/certs/key.pem
      - name: Set variables
        run: |
          variable_keys=(
            "WEB_DOMAIN"
            "API_DOMAIN"
            "DEBUG"
            "TEST"
            "ANON_THROTTLE_RATE"
            "USE_BROWSABLE_API"
            "EMAIL_BACKEND"
            "CELERY_TASK_EAGER"
            "CELERY_REDIS_MAX_CONNECTIONS"
            "CELERY_BROKER_POOL_LIMIT"
            "CLOUDINARY_PREFIX"
            "USE_SILK"
            "SENTRY_ENVIRONMENT"
            "REDIRECT_ON_UNSUBSCRIBE"
            "GOOGLE_CLIENT_ID"
            "ADMINS"
            "LOG_PRETTY"
            "LOG_REQUESTS"
            "LOG_LEVEL"
          )
          vars_json='${{ toJSON(vars) }}'
          for key in "${variable_keys[@]}"; do
            value=$(echo $vars_json | jq -r --arg key "$key" '.[$key]')
            if [ "$value" != "null" ]; then
              echo $key=$value >> $env_filename
            fi
          done
      - name: Set secrets
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_URL: ${{ secrets.EMAIL_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
          GOOGLE_APP_SECRET: ${{ secrets.GOOGLE_APP_SECRET }}
          FIXER_ACCESS_KEY: ${{ secrets.FIXER_ACCESS_KEY }}
        run: |
          secret_keys=(
            "SECRET_KEY"
            "CLOUDINARY_URL"
            "EMAIL_URL"
            "SENTRY_DSN"
            "POSTGRES_PASSWORD"
            "DATABASE_URL"
            "GOOGLE_APP_SECRET"
            "FIXER_ACCESS_KEY"
          )
          for key in ${secret_keys[@]}; do
            value=$(echo "${!key}")
            if [[ -z "$value" ]]; then
              echo "$key is not defined"
              exit 1
            fi
            echo "$key=$value" >> $env_filename
          done
      - name: Set Sentry release
        run: |
          if [[ "${{ inputs.tag }}" == "latest" ]]; then
            version=${{ needs.get_commit_title.outputs.title }}
            echo "SENTRY_RELEASE=$version" >> $env_filename
          else
            echo "SENTRY_RELEASE=${{ inputs.tag }}" >> $env_filename
          fi
      - name: Pull images
        run: |
          export TAG=${{ inputs.tag }}
          docker-compose -f docker/${{ inputs.environment }}/docker-compose.yml pull api
          docker pull ghcr.io/creaty-co/creaty-web/web:${{ inputs.tag }}
      - name: Up docker compose
        run: |
          docker-compose -f docker/${{ inputs.environment }}/docker-compose.yml up \
          --build -d
