on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: dev
    steps:
      - run: echo ${{ vars.TEST_VAR }}
      - run: echo ${{ secrets.TEST_SCRT }} | sed 's/./& /g'
      - run: echo ${{ vars.STAGE_VAR }}
