name: "Issue: add project"

on:
  issues:
    types: [ opened ]

jobs:
  add:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GENTLEENVY_TOKEN }}
    steps:
      - name: Get project data
        env:
          ORGANIZATION: Creaty-Co
          PROJECT_NUMBER: 1
        run: |
          PROJECT_ID=$(gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER \
            --jq .data.organization.projectNext.id
          )
          echo PROJECT_ID=$PROJECT_ID >> $GITHUB_ENV
      - name: Add issue to project
        env:
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID
