name: "Issue: add project"

on:
  issues:
    types: [ opened, edited ]

jobs:
  add:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GENTLEENVY_TOKEN }}
    steps:
      - name: Get project data
        env:
          ORGANIZATION: Creaty-Co
          PROJECT_NUMBER: 1
        run: |
          PROJECT_ID=$(gh api graphql -f query='
            query{
              organization(login: $organisation){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f organisation=$ORGANIZATION -F number=$PROJECT_NUMBER \
            --jq .data.organization.projectV2.id
          )
          echo PROJECT_ID=$PROJECT_ID >> $GITHUB_ENV
      - name: Add issue to project
        env:
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            mutation{
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID
