name: "Issue: assign"

on:
  issues:
    types: [ opened ]

jobs:
  assign:
    runs-on: ubuntu-22.04
    steps:
      - uses: pozil/auto-assign-issue@v2.0.0
        with:
          assignees: GentleEnvy
          abortIfPreviousAssignees: true
