name: "PR: add labels"

on:
  pull_request:

permissions:
    contents: read
    pull-requests: write

jobs:
  add:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@4.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: false
