name: "PR: check labels"

on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize, ready_for_review ]

jobs:
  check:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: task,test,bug,dependencies,devops
          repo_token: ${{ secrets.GITHUB_TOKEN }}
