name: "Push: main"

on:
  push:
    branches:    
      - 'main'

jobs:
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
  build:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/call-deploy_dev.yml
    secrets: inherit
    needs: [ build ]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: dev
    secrets: inherit
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [ update_prs ]
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
