name: "Push: main"

on:
  push:
    branches:
      - 'main'

jobs:
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
  build:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
  build_sha:
    uses: ./.github/workflows/call-build.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit
  deploy:
    uses: ./.github/workflows/call-deploy.yml
    with:
      environment: dev
      url: 'https://dev.creaty.club'
    secrets: inherit
    needs: [build]
  update_version:
    uses: ./.github/workflows/call-update_version.yml
    with:
      version: ${{ github.sha }}
    secrets: inherit
    needs: [build_sha]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: dev
    secrets: inherit
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [update_prs]
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
