name: "Push: main"

on:
  push:
    branches:    
      - 'main'

jobs:
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
  build:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/call-deploy_stage.yml
    secrets: inherit
    needs: [ build ]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: stage
    secrets: inherit
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [ update_prs ]
