name: "Push: not main"

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
# FIXME
  bw:
    uses: ./.github/workflows/call-bw.yml
    with:
      secret_name: TEST
    secrets: inherit
  echo:
    runs-on: self-hosted
    needs: bw
    env:
      STAGE_ENV: ${{ needs.bw.outputs.secret_value }}
    steps:
      - run: |
          echo $STAGE_ENV
          echo -e ${{ env.STAGE_ENV }} > .env
