name: "Push: main"

on:
  push:
    branches:    
      - 'main'

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
