name: "Release: edited"

on:
  release:
    types: [ edited ]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    uses: ./.github/workflows/call-deploy.yml
    with:
      environment: prod
      url: 'https://creaty.club'
      tag: ${{ github.ref_name }}
    secrets: inherit
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: prod
      version: ${{ github.ref_name }}
    secrets: inherit
    needs: [ deploy ]
