name: "Release: edited"

on:
  release:
    types: [ edited ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.release }}
          echo ${{ github.event.release.latest }}
          echo ${{ github.event.release.is_latest }}
          echo ${{ github.event.release.isLatest }}
          echo ${{ github.event.release.prerelease }}
          echo ${{ github.event.release.isPrerelease }}
  deploy:
    if: "github.event.release.is_latest"
    uses: ./.github/workflows/call-deploy.yml
    with:
      environment: prod
      url: 'https://creaty.club'
      tag: ${{ github.ref_name }}
    secrets: inherit
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: prod
      version: ${{ github.ref_name }}
    secrets: inherit
    needs: [ deploy ]
