name: "Release: published"

on:
  release:
    types: [ published ]

jobs:
  build:
    if: "!github.event.release.prerelease"
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
  deploy:
    uses: ./.github/workflows/call-deploy.yml
    with:
      environment: prod
      url: 'https://creaty.club'
      tag: ${{ github.ref_name }}
    secrets: inherit
    needs: [ build ]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: prod
      version: ${{ github.ref_name }}
    secrets: inherit
    needs: [ cd ]
