name: "Release: published"

on:
  release:
    types: [ published ]

jobs:
  build:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
  deploy:
    uses: ./.github/workflows/call-deploy.yml
    with:
      environment: stage
      url: 'https://stage.creaty.club'
      tag: ${{ github.ref_name }}
      web_tag: pre-${{ github.ref_name }}
    secrets: inherit
    needs: [ build ]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: stage
      version: pre-${{ github.ref_name }}
    secrets: inherit
    needs: [ deploy ]
