on:
  push:
    branches:
      - task-275

jobs:
  test:
    uses: ./.github/workflows/call-ci.yml
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: dev
    steps:
      - run: echo ${{ vars.TEST_VAR }}
