# Generated by Django 4.2.3 on 2023-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlybooking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trialbooking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
